/**
 * Curated Phosphor icon registry.
 *
 * The app resolves `phosphor:<name>` strings (route icons, folder icons picked
 * in the sidebar header) to React components. Importing the whole
 * `@phosphor-icons/react` namespace defeats tree-shaking and inflates the
 * single-file app bundle from ~200 kB to ~5.9 MB, so we import an explicit,
 * curated set instead. Every name below is also what the folder icon picker
 * offers, so the picker and the resolver can never drift apart.
 *
 * Generated list — keep alphabetically grouped by theme and add names here when
 * the picker should offer more.
 */
import type { Icon } from '@phosphor-icons/react';
import {
  FolderIcon,
  FolderOpenIcon,
  FolderSimpleIcon,
  FolderStarIcon,
  FolderUserIcon,
  FolderLockIcon,
  FolderPlusIcon,
  FolderNotchIcon,
  ArchiveIcon,
  BookmarkIcon,
  BookmarkSimpleIcon,
  BookmarksIcon,
  BookIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BookBookmarkIcon,
  BooksIcon,
  NotebookIcon,
  NoteIcon,
  NoteBlankIcon,
  NotePencilIcon,
  NotepadIcon,
  PencilIcon,
  PencilSimpleIcon,
  PenIcon,
  PenNibIcon,
  FileIcon,
  FileTextIcon,
  FileDocIcon,
  FilePdfIcon,
  FilesIcon,
  PaperclipIcon,
  PushPinIcon,
  ClipboardIcon,
  ClipboardTextIcon,
  ListChecksIcon,
  ListBulletsIcon,
  ListNumbersIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  TargetIcon,
  FlagIcon,
  TrophyIcon,
  MedalIcon,
  StarIcon,
  HeartIcon,
  SmileyIcon,
  LightbulbIcon,
  SparkleIcon,
  MagicWandIcon,
  BrainIcon,
  GraduationCapIcon,
  StudentIcon,
  ChalkboardTeacherIcon,
  CertificateIcon,
  BriefcaseIcon,
  SuitcaseIcon,
  SuitcaseRollingIcon,
  BuildingsIcon,
  BankIcon,
  MoneyIcon,
  CoinsIcon,
  CreditCardIcon,
  ReceiptIcon,
  InvoiceIcon,
  CalculatorIcon,
  HandshakeIcon,
  ChartLineIcon,
  ChartBarIcon,
  ChartPieSliceIcon,
  TrendUpIcon,
  PresentationChartIcon,
  TableIcon,
  ColumnsIcon,
  RowsIcon,
  KanbanIcon,
  TreeStructureIcon,
  GraphIcon,
  FlowArrowIcon,
  StackIcon,
  CubeIcon,
  SquaresFourIcon,
  UsersIcon,
  UserIcon,
  UserCircleIcon,
  UserFocusIcon,
  UserGearIcon,
  IdentificationCardIcon,
  AddressBookIcon,
  ChatsIcon,
  ChatCircleIcon,
  ChatTextIcon,
  ChatTeardropTextIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  TrayIcon,
  PhoneIcon,
  VideoCameraIcon,
  MicrophoneIcon,
  MegaphoneIcon,
  BroadcastIcon,
  BellIcon,
  BellRingingIcon,
  CalendarIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CalendarDotsIcon,
  ClockIcon,
  AlarmIcon,
  TimerIcon,
  HourglassIcon,
  HouseIcon,
  HouseLineIcon,
  DoorIcon,
  BedIcon,
  CouchIcon,
  BathtubIcon,
  CookingPotIcon,
  ForkKnifeIcon,
  CoffeeIcon,
  WineIcon,
  PizzaIcon,
  HamburgerIcon,
  CarrotIcon,
  AppleLogoIcon,
  BreadIcon,
  CakeIcon,
  HeartbeatIcon,
  FirstAidIcon,
  PillIcon,
  BarbellIcon,
  PersonSimpleRunIcon,
  BicycleIcon,
  SneakerIcon,
  LeafIcon,
  TreeIcon,
  PlantIcon,
  FlowerIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  DropIcon,
  MountainsIcon,
  GlobeIcon,
  CompassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  AirplaneIcon,
  CarIcon,
  TrainIcon,
  BoatIcon,
  SailboatIcon,
  RocketIcon,
  CameraIcon,
  ImageIcon,
  ImagesIcon,
  PlayIcon,
  VideoIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  HeadphonesIcon,
  SpeakerHighIcon,
  RadioIcon,
  VinylRecordIcon,
  GuitarIcon,
  PianoKeysIcon,
  FilmSlateIcon,
  TelevisionIcon,
  GameControllerIcon,
  PaletteIcon,
  PaintBrushIcon,
  ScissorsIcon,
  RulerIcon,
  CropIcon,
  CodeIcon,
  BracketsCurlyIcon,
  TerminalIcon,
  BugIcon,
  GitBranchIcon,
  DatabaseIcon,
  HardDrivesIcon,
  CloudArrowUpIcon,
  CpuIcon,
  DesktopIcon,
  LaptopIcon,
  DeviceMobileIcon,
  PlugIcon,
  LightningIcon,
  BatteryChargingIcon,
  GearIcon,
  SlidersHorizontalIcon,
  WrenchIcon,
  HammerIcon,
  ToolboxIcon,
  KeyIcon,
  LockIcon,
  LockOpenIcon,
  ShieldIcon,
  ShieldCheckIcon,
  FingerprintIcon,
  EyeIcon,
  EyeSlashIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  SortAscendingIcon,
  TagIcon,
  HashIcon,
  AtIcon,
  LinkIcon,
  PaperPlaneTiltIcon,
  ShareNetworkIcon,
  DownloadIcon,
  UploadIcon,
  TrashIcon,
  RecycleIcon,
  PackageIcon,
  ShoppingCartIcon,
  ShoppingBagIcon,
  StorefrontIcon,
  GiftIcon,
  TicketIcon,
  NewspaperIcon,
  ArticleIcon,
  ScrollIcon,
  QuotesIcon,
  TranslateIcon,
  InfinityIcon,
  PuzzlePieceIcon,
  ArrowsClockwiseIcon,
  RepeatIcon,
  ShuffleIcon,
  QuestionIcon,
  InfoIcon,
  WarningIcon,
  SealCheckIcon,
  ThumbsUpIcon,
  FireIcon,
  SnowflakeIcon,
  UmbrellaIcon,
  WindIcon,
  WavesIcon,
  AnchorIcon,
  LifebuoyIcon,
  PawPrintIcon,
  DogIcon,
  CatIcon,
  ButterflyIcon,
  BirdIcon,
  FishIcon,
  CampfireIcon,
  TentIcon,
  BinocularsIcon,
  AtomIcon,
  FlaskIcon,
  TestTubeIcon,
  MicroscopeIcon,
  DnaIcon,
  GavelIcon,
  ScalesIcon,
  StethoscopeIcon,
  BabyIcon,
  ConfettiIcon,
  BalloonIcon,
  ChampagneIcon,
  MartiniIcon,
  DiceFiveIcon,
  PokerChipIcon,
  HandHeartIcon,
  HandsPrayingIcon,
  PersonIcon,
  CrownIcon,
  GhostIcon,
  AlienIcon,
  RobotIcon,
} from '@phosphor-icons/react';

export const PHOSPHOR_ICONS: Record<string, Icon> = {
  'folder': FolderIcon,
  'folder-open': FolderOpenIcon,
  'folder-simple': FolderSimpleIcon,
  'folder-star': FolderStarIcon,
  'folder-user': FolderUserIcon,
  'folder-lock': FolderLockIcon,
  'folder-plus': FolderPlusIcon,
  'folder-notch': FolderNotchIcon,
  'archive': ArchiveIcon,
  'bookmark': BookmarkIcon,
  'bookmark-simple': BookmarkSimpleIcon,
  'bookmarks': BookmarksIcon,
  'book': BookIcon,
  'book-open': BookOpenIcon,
  'book-open-text': BookOpenTextIcon,
  'book-bookmark': BookBookmarkIcon,
  'books': BooksIcon,
  'notebook': NotebookIcon,
  'note': NoteIcon,
  'note-blank': NoteBlankIcon,
  'note-pencil': NotePencilIcon,
  'notepad': NotepadIcon,
  'pencil': PencilIcon,
  'pencil-simple': PencilSimpleIcon,
  'pen': PenIcon,
  'pen-nib': PenNibIcon,
  'file': FileIcon,
  'file-text': FileTextIcon,
  'file-doc': FileDocIcon,
  'file-pdf': FilePdfIcon,
  'files': FilesIcon,
  'paperclip': PaperclipIcon,
  'push-pin': PushPinIcon,
  'clipboard': ClipboardIcon,
  'clipboard-text': ClipboardTextIcon,
  'list-checks': ListChecksIcon,
  'list-bullets': ListBulletsIcon,
  'list-numbers': ListNumbersIcon,
  'check-circle': CheckCircleIcon,
  'check-square': CheckSquareIcon,
  'target': TargetIcon,
  'flag': FlagIcon,
  'trophy': TrophyIcon,
  'medal': MedalIcon,
  'star': StarIcon,
  'heart': HeartIcon,
  'smiley': SmileyIcon,
  'lightbulb': LightbulbIcon,
  'sparkle': SparkleIcon,
  'magic-wand': MagicWandIcon,
  'brain': BrainIcon,
  'graduation-cap': GraduationCapIcon,
  'student': StudentIcon,
  'chalkboard-teacher': ChalkboardTeacherIcon,
  'certificate': CertificateIcon,
  'briefcase': BriefcaseIcon,
  'suitcase': SuitcaseIcon,
  'suitcase-rolling': SuitcaseRollingIcon,
  'buildings': BuildingsIcon,
  'bank': BankIcon,
  'money': MoneyIcon,
  'coins': CoinsIcon,
  'credit-card': CreditCardIcon,
  'receipt': ReceiptIcon,
  'invoice': InvoiceIcon,
  'calculator': CalculatorIcon,
  'handshake': HandshakeIcon,
  'chart-line': ChartLineIcon,
  'chart-bar': ChartBarIcon,
  'chart-pie-slice': ChartPieSliceIcon,
  'trend-up': TrendUpIcon,
  'presentation-chart': PresentationChartIcon,
  'table': TableIcon,
  'columns': ColumnsIcon,
  'rows': RowsIcon,
  'kanban': KanbanIcon,
  'tree-structure': TreeStructureIcon,
  'graph': GraphIcon,
  'flow-arrow': FlowArrowIcon,
  'stack': StackIcon,
  'cube': CubeIcon,
  'squares-four': SquaresFourIcon,
  'users': UsersIcon,
  'user': UserIcon,
  'user-circle': UserCircleIcon,
  'user-focus': UserFocusIcon,
  'user-gear': UserGearIcon,
  'identification-card': IdentificationCardIcon,
  'address-book': AddressBookIcon,
  'chats': ChatsIcon,
  'chat-circle': ChatCircleIcon,
  'chat-text': ChatTextIcon,
  'chat-teardrop-text': ChatTeardropTextIcon,
  'envelope': EnvelopeIcon,
  'envelope-simple': EnvelopeSimpleIcon,
  'tray': TrayIcon,
  'phone': PhoneIcon,
  'video-camera': VideoCameraIcon,
  'microphone': MicrophoneIcon,
  'megaphone': MegaphoneIcon,
  'broadcast': BroadcastIcon,
  'bell': BellIcon,
  'bell-ringing': BellRingingIcon,
  'calendar': CalendarIcon,
  'calendar-blank': CalendarBlankIcon,
  'calendar-check': CalendarCheckIcon,
  'calendar-dots': CalendarDotsIcon,
  'clock': ClockIcon,
  'alarm': AlarmIcon,
  'timer': TimerIcon,
  'hourglass': HourglassIcon,
  'house': HouseIcon,
  'house-line': HouseLineIcon,
  'door': DoorIcon,
  'bed': BedIcon,
  'couch': CouchIcon,
  'bathtub': BathtubIcon,
  'cooking-pot': CookingPotIcon,
  'fork-knife': ForkKnifeIcon,
  'coffee': CoffeeIcon,
  'wine': WineIcon,
  'pizza': PizzaIcon,
  'hamburger': HamburgerIcon,
  'carrot': CarrotIcon,
  'apple-logo': AppleLogoIcon,
  'bread': BreadIcon,
  'cake': CakeIcon,
  'heartbeat': HeartbeatIcon,
  'first-aid': FirstAidIcon,
  'pill': PillIcon,
  'barbell': BarbellIcon,
  'person-simple-run': PersonSimpleRunIcon,
  'bicycle': BicycleIcon,
  'sneaker': SneakerIcon,
  'leaf': LeafIcon,
  'tree': TreeIcon,
  'plant': PlantIcon,
  'flower': FlowerIcon,
  'sun': SunIcon,
  'moon': MoonIcon,
  'cloud': CloudIcon,
  'drop': DropIcon,
  'mountains': MountainsIcon,
  'globe': GlobeIcon,
  'compass': CompassIcon,
  'map-pin': MapPinIcon,
  'map-trifold': MapTrifoldIcon,
  'airplane': AirplaneIcon,
  'car': CarIcon,
  'train': TrainIcon,
  'boat': BoatIcon,
  'sailboat': SailboatIcon,
  'rocket': RocketIcon,
  'camera': CameraIcon,
  'image': ImageIcon,
  'images': ImagesIcon,
  'play': PlayIcon,
  'video': VideoIcon,
  'music-note': MusicNoteIcon,
  'music-notes': MusicNotesIcon,
  'headphones': HeadphonesIcon,
  'speaker-high': SpeakerHighIcon,
  'radio': RadioIcon,
  'vinyl-record': VinylRecordIcon,
  'guitar': GuitarIcon,
  'piano-keys': PianoKeysIcon,
  'film-slate': FilmSlateIcon,
  'television': TelevisionIcon,
  'game-controller': GameControllerIcon,
  'palette': PaletteIcon,
  'paint-brush': PaintBrushIcon,
  'scissors': ScissorsIcon,
  'ruler': RulerIcon,
  'crop': CropIcon,
  'code': CodeIcon,
  'brackets-curly': BracketsCurlyIcon,
  'terminal': TerminalIcon,
  'bug': BugIcon,
  'git-branch': GitBranchIcon,
  'database': DatabaseIcon,
  'hard-drives': HardDrivesIcon,
  'cloud-arrow-up': CloudArrowUpIcon,
  'cpu': CpuIcon,
  'desktop': DesktopIcon,
  'laptop': LaptopIcon,
  'device-mobile': DeviceMobileIcon,
  'plug': PlugIcon,
  'lightning': LightningIcon,
  'battery-charging': BatteryChargingIcon,
  'gear': GearIcon,
  'sliders-horizontal': SlidersHorizontalIcon,
  'wrench': WrenchIcon,
  'hammer': HammerIcon,
  'toolbox': ToolboxIcon,
  'key': KeyIcon,
  'lock': LockIcon,
  'lock-open': LockOpenIcon,
  'shield': ShieldIcon,
  'shield-check': ShieldCheckIcon,
  'fingerprint': FingerprintIcon,
  'eye': EyeIcon,
  'eye-slash': EyeSlashIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  'funnel': FunnelIcon,
  'sort-ascending': SortAscendingIcon,
  'tag': TagIcon,
  'hash': HashIcon,
  'at': AtIcon,
  'link': LinkIcon,
  'paper-plane-tilt': PaperPlaneTiltIcon,
  'share-network': ShareNetworkIcon,
  'download': DownloadIcon,
  'upload': UploadIcon,
  'trash': TrashIcon,
  'recycle': RecycleIcon,
  'package': PackageIcon,
  'shopping-cart': ShoppingCartIcon,
  'shopping-bag': ShoppingBagIcon,
  'storefront': StorefrontIcon,
  'gift': GiftIcon,
  'ticket': TicketIcon,
  'newspaper': NewspaperIcon,
  'article': ArticleIcon,
  'scroll': ScrollIcon,
  'quotes': QuotesIcon,
  'translate': TranslateIcon,
  'infinity': InfinityIcon,
  'puzzle-piece': PuzzlePieceIcon,
  'arrows-clockwise': ArrowsClockwiseIcon,
  'repeat': RepeatIcon,
  'shuffle': ShuffleIcon,
  'question': QuestionIcon,
  'info': InfoIcon,
  'warning': WarningIcon,
  'seal-check': SealCheckIcon,
  'thumbs-up': ThumbsUpIcon,
  'fire': FireIcon,
  'snowflake': SnowflakeIcon,
  'umbrella': UmbrellaIcon,
  'wind': WindIcon,
  'waves': WavesIcon,
  'anchor': AnchorIcon,
  'lifebuoy': LifebuoyIcon,
  'paw-print': PawPrintIcon,
  'dog': DogIcon,
  'cat': CatIcon,
  'butterfly': ButterflyIcon,
  'bird': BirdIcon,
  'fish': FishIcon,
  'campfire': CampfireIcon,
  'tent': TentIcon,
  'binoculars': BinocularsIcon,
  'atom': AtomIcon,
  'flask': FlaskIcon,
  'test-tube': TestTubeIcon,
  'microscope': MicroscopeIcon,
  'dna': DnaIcon,
  'gavel': GavelIcon,
  'scales': ScalesIcon,
  'stethoscope': StethoscopeIcon,
  'baby': BabyIcon,
  'confetti': ConfettiIcon,
  'balloon': BalloonIcon,
  'champagne': ChampagneIcon,
  'martini': MartiniIcon,
  'dice-five': DiceFiveIcon,
  'poker-chip': PokerChipIcon,
  'hand-heart': HandHeartIcon,
  'hands-praying': HandsPrayingIcon,
  'person': PersonIcon,
  'crown': CrownIcon,
  'ghost': GhostIcon,
  'alien': AlienIcon,
  'robot': RobotIcon,
};

/** Alternate slugs so icons stored under other naming schemes still resolve. */
export const PHOSPHOR_ICON_ALIASES: Record<string, string> = {
  boxes: 'cube',
  'calendar-days': 'calendar',
  'layout-grid': 'squares-four',
  'layout-dashboard': 'squares-four',
  'link-2': 'link',
  'notebook-pen': 'note-pencil',
  'rows-3': 'rows',
  search: 'magnifying-glass',
  'settings-2': 'sliders-horizontal',
  settings: 'gear',
  sparkles: 'sparkle',
  'sticky-note': 'note',
  'table-2': 'table',
  home: 'house',
  'folder-kanban': 'kanban',
  mail: 'envelope',
  'message-square': 'chat-text',
  'messages-square': 'chats',
  zap: 'lightning',
  bot: 'robot',
  inbox: 'tray',
  puzzle: 'puzzle-piece',
  'file-doc-x': 'file-doc',
};

export const PHOSPHOR_ICON_NAMES: string[] = Object.keys(PHOSPHOR_ICONS);
